import 'code_stats.dart';
import 'github_stats.dart';
import 'pub_stats.dart';

/// One quantified proof point — a number, what it counts, and (optionally)
/// the context that makes it credible rather than just large.
class Metric {
  const Metric({required this.value, required this.label, this.detail});

  /// The number itself, pre-formatted for display (e.g. '25M+', '1.3M').
  final String value;

  /// What the number counts, in two or three words.
  final String label;

  /// The longer "and here's why that's true" line. Shown in human mode and
  /// the terminal's `metrics` command, omitted from the compact hero band.
  final String? detail;
}

/// The four numbers that lead the site — the ones a hiring manager should
/// see without typing a command or scrolling.
final headlineMetrics = <Metric>[
  const Metric(
    value: '25M+',
    label: 'users reached',
    detail: "Couchsurfing's global member base, served by the mobile app I architected.",
  ),
  Metric(
    value: '${compactCount(pubDownloads30Days)}/mo',
    label: 'package downloads',
    detail: '$pubPackageCount packages published to pub.dev, pulled fresh from the pub.dev API on every build.',
  ),
  Metric(
    value: compactCount(totalCodeLines),
    label: 'lines written',
    detail:
        'Hand-written source across 94 non-fork repositories plus the Couchsurfing app — '
        'counted with scc, excluding generated, vendored, and built output.',
  ),
  Metric(
    value: _thousands(ghContributionsLastYear),
    label: 'contributions this year',
    detail:
        '${_thousands(ghCommitsLastYear)} commits and ${_thousands(ghReviewsLastYear)} code reviews '
        'in the last 12 months, pulled from the GitHub API on every build.',
  ),
];

/// What the work actually produced — revenue, ratings, growth, throughput.
/// The numbers that answer "did any of it matter?".
const impactMetrics = <Metric>[
  Metric(
    value: r'$1M+',
    label: 'annual revenue',
    detail: 'Yearly revenue generated by the Clean Simple Eats app I built and maintained.',
  ),
  Metric(
    value: '9',
    label: 'engineers led',
    detail: 'The mobile team I lead and mentor, setting technical direction and engineering standards.',
  ),
  Metric(
    value: '1.3M',
    label: 'lines architected',
    detail: 'The Couchsurfing Flutter app specifically, from an empty repo to a production codebase.',
  ),
  Metric(
    value: '4.8★',
    label: 'app store rating',
    detail: 'Clean Simple Eats, averaged across 5,700+ App Store ratings.',
  ),
  Metric(
    value: '5×',
    label: 'user growth',
    detail: 'Grew Clean Simple Eats from ~2K to 10K+ monthly active users as the sole developer.',
  ),
  Metric(
    value: '2,382',
    label: 'pull requests reviewed',
    detail: 'Code review on the Couchsurfing monorepo — 67 contributors, 13K+ pull requests.',
  ),
  Metric(
    value: '947',
    label: 'pull requests shipped',
    detail: '913 of them merged, alongside 1,100+ commits to the Couchsurfing codebase.',
  ),
  Metric(
    value: '2 weeks',
    label: 'release cadence',
    detail: 'Sustained a two-week iOS and Android release cycle for 3.5 years.',
  ),
];

/// The open-source body of work, and how active it actually is — the part
/// anyone can go verify in about thirty seconds.
final openSourceMetrics = <Metric>[
  const Metric(
    value: '8+',
    label: 'years in dart & flutter',
    detail: 'Shipping production Flutter since well before it was a safe choice.',
  ),
  Metric(
    value: '$pubPackageCount',
    label: 'packages published',
    detail: 'On pub.dev, including two full backend frameworks built end to end.',
  ),
  Metric(
    value: compactCount(personalCodeLines),
    label: 'lines of my own code',
    detail: 'Across my own projects alone — 459K of it Dart — separate from anything built at work.',
  ),
  const Metric(
    value: '$ghPublicRepos',
    label: 'public repositories',
    detail: 'Non-fork and publicly readable, of 94 total — 51 of them Dart.',
  ),
  const Metric(
    value: '6',
    label: 'perfect pub scores',
    detail: 'Packages holding a full 160/160 on pub.dev for docs, conventions, and analysis.',
  ),
  const Metric(
    value: '2',
    label: 'backend frameworks',
    detail: 'Revali and Zonai — both published, both documented, both built end to end.',
  ),
];

/// Thousands separators, since these are read as quantities rather than
/// skimmed as headline figures (where [compactCount] is the better fit).
String _thousands(int n) {
  final digits = n.toString();
  final buffer = StringBuffer();
  for (var i = 0; i < digits.length; i++) {
    if (i > 0 && (digits.length - i) % 3 == 0) buffer.write(',');
    buffer.write(digits[i]);
  }
  return buffer.toString();
}
